In [1]:
from keras.src.metrics.accuracy_metrics import accuracy
from sklearn.metrics import accuracy_score
from sympy.conftest import pytest_report_header


def warn (*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [2]:
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

In [3]:
my_data = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/drug200.csv', delimiter=",")
my_data.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [4]:
my_data.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [5]:
my_data.size

1200

In [6]:
my_data.shape

(200, 6)

In [ ]:
my_data.columns

In [7]:
my_data.dtypes

Age              int64
Sex             object
BP              object
Cholesterol     object
Na_to_K        float64
Drug            object
dtype: object

In [8]:
#preprocessing

In [10]:
X = my_data[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values # chuyển my_data về mảng pandas
X[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.114],
       [28, 'F', 'NORMAL', 'HIGH', 7.798],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [11]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
X[:,1] = le_sex.transform(X[:,1])

le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
X[:,2] = le_BP.transform(X[:,2])

le_Cholesterol = preprocessing.LabelEncoder()
le_Cholesterol.fit([ 'NORMAL', 'HIGH'])
X[:,3] = le_Cholesterol.transform(X[:,3])
X[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [13]:
y = my_data["Drug"]
y[0:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object

In [14]:
# Setting up the Decition Tree

In [15]:
from sklearn.model_selection import train_test_split


In [16]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)

In [18]:
print(X_trainset.shape)
print(y_trainset.shape)

(140, 5)
(140,)


In [19]:
print('Shape of X training set {}'.format(X_trainset.shape),'&',' Size of Y training set {}'.format(y_trainset.shape))

Shape of X training set (140, 5) &  Size of Y training set (140,)


In [20]:
print(X_testset.shape)
print(y_testset.shape)


(60, 5)
(60,)


In [21]:
# Build Modeling

In [22]:
drupTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
drupTree


DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [23]:
drupTree.fit(X_trainset,y_trainset)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [24]:
# Dự đoán mô hình
predicTree = drupTree.predict(X_testset)

In [27]:
print (predicTree [0:20])
print (y_testset [0:20])

['drugY' 'drugX' 'drugX' 'drugX' 'drugX' 'drugC' 'drugY' 'drugA' 'drugB'
 'drugA' 'drugY' 'drugA' 'drugY' 'drugY' 'drugX' 'drugY' 'drugX' 'drugX'
 'drugB' 'drugX']
40     drugY
51     drugX
139    drugX
197    drugX
170    drugX
82     drugC
183    drugY
46     drugA
70     drugB
100    drugA
179    drugY
83     drugA
25     drugY
190    drugY
159    drugX
173    drugY
95     drugX
3      drugX
41     drugB
58     drugX
Name: Drug, dtype: object


In [31]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_testset, predicTree)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[ 7  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 20  1]
 [ 0  0  0  0 22]]


In [32]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_testset, predicTree)
print(f"Accuracy: {accuracy:.2f}")


Accuracy: 0.98


In [34]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predicTree))

DecisionTrees's Accuracy:  0.9833333333333333


In [36]:
from sklearn.tree import export_graphviz
export_graphviz(drupTree, out_file='tree.dot', filled=True, feature_names=['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K'])

In [37]:
!dot -Tpng tree.dot -o tree.png