In [11]:
import numpy as np
from pandas.core.interchange.from_dataframe import primitive_column_to_ndarray


def solution(A):
    # Chuyển thành NumPy array và lọc số nguyên dương
    A = np.array(A)
    A = A[A > 0]  # Giữ số lớn hơn 0

    if A.size == 0:  # Nếu danh sách rỗng, trả về 1
        return 1

    # Sắp xếp và loại bỏ số trùng
    sort_a = np.sort(np.unique(A))
    print(sort_a)

    # Kiểm tra số nhỏ nhất bị thiếu
    loss_number = 1
    for num in sort_a:
        if num == loss_number:
            loss_number += 1
        else:
            break  # Nếu số tiếp theo bị thiếu, return ngay

    return loss_number

# Test cases
print(solution([1, 3, 6, 4, 1, 2]))  # Output: 5
print(solution([1, 2, 3]))          # Output: 4
print(solution([-1, 1000]))           # Output: 1
print(solution([5, 6, 7, 8]))       # Output: 1
print(solution([2, 3, 4]))          # Output: 1


[1 2 3 4 6]
5
[1 2 3]
4
[1000]
1
[5 6 7 8]
1
[2 3 4]
1


In [14]:
def is_square(X, Y):
    # Bước 1: Xác định min/max của X và Y
    X_min, X_max = min(X), max(X)
    Y_min, Y_max = min(Y), max(Y)

    # Bước 2: Kiểm tra điều kiện hình vuông
    if (X_max - X_min) != (Y_max - Y_min):
        return False  # Không thể tạo thành hình vuông

    # Bước 3: Kiểm tra xem tất cả các điểm có nằm trên cạnh hình vuông không
    for x, y in zip(X, Y):
        if not (x == X_min or x == X_max or y == Y_min or y == Y_max):
            return False  # Nếu có điểm nào không nằm trên cạnh -> không hợp lệ

    return True  # Nếu tất cả điểm đều nằm trên cạnh -> Hợp lệ

# 🔹 Test cases
X1, Y1 = [0, 0, -1, 2, 1, 1], [0, 2, 0, 2, 0, 2]  # True (hình vuông cạnh 2)
X2, Y2 = [0, 0, 3, 3, 1, 2], [0, 3, 0, 3, 0, 3]  # False (hình chữ nhật)
X3, Y3 = [1, 1, 4, 4, 2, 3], [1, 4, 1, 4, 1, 4]  # True (hình vuông cạnh 3)

print(is_square(X1, Y1))  # Output: True
print(is_square(X2, Y2))  # Output: False
print(is_square(X3, Y3))  # Output: True


False
True
True


In [15]:
def is_valid_square(X, Y):
    # Nếu có ít hơn 3 điểm, không thể tạo thành hình vuông
    if len(X) < 3:
        return False

    # Tìm giá trị min/max của X và Y
    X_min, X_max = min(X), max(X)
    Y_min, Y_max = min(Y), max(Y)

    # Biến kiểm tra xem có ít nhất 1 điểm thuộc biên hình vuông không
    has_x_max, has_y_max = False, False

    # Kiểm tra từng điểm (x, y)
    for x, y in zip(X, Y):
        if x > 0 and x != X_max:  # Điểm x > 0 nhưng không thuộc X_max
            return False
        if x < 0 and x != X_min:  # Điểm x < 0 nhưng không thuộc X_min
            return False
        if y > 0 and y != Y_max:  # Điểm y > 0 nhưng không thuộc Y_max
            return False
        if y < 0 and y != Y_min:  # Điểm y < 0 nhưng không thuộc Y_min
            return False

        # Đánh dấu nếu có điểm thuộc X_max hoặc Y_max
        if x == X_max:
            has_x_max = True
        if y == Y_max:
            has_y_max = True

    # Nếu có đúng 3 điểm, chỉ cần 1 điểm thuộc X_max hoặc Y_max
    if len(X) == 3 and (has_x_max or has_y_max):
        return True

    # Nếu có 4 điểm trở lên, tất cả phải nằm trên biên hình vuông
    return True

# 🔹 Test cases
X1, Y1 = [-1, 1, -2], [2, 1, 0]  # ✅ True (Hình vuông có 3 điểm)
X2, Y2 = [1, 2, 3], [1, 2, 3]  # ❌ False (Không nằm trên biên)
X3, Y3 = [-2, -1, 1, 2], [0, 2, 2, 0]  # ✅ True (Hình vuông hoàn chỉnh)
X4, Y4 = [-1, 1, -2, 1], [2, 1, 0, 0]  # ✅ True (Hình vuông hợp lệ)

print(is_valid_square(X1, Y1))  # ✅ True
print(is_valid_square(X2, Y2))  # ❌ False
print(is_valid_square(X3, Y3))  # ✅ True
print(is_valid_square(X4, Y4))  # ✅ True




False
False
False
False


In [17]:
import numpy as np

def solution(S):
    # Bước 1: Tách chuỗi thành mảng NumPy
    arr = np.array(list(S))

    # Bước 2: Đếm số lần xuất hiện của mỗi ký tự
    unique_chars, counts = np.unique(arr, return_counts=True)

    # Lưu trữ số lần xuất hiện dưới dạng dictionary {char: count}
    freq_dict = dict(zip(unique_chars, counts))

    palindrome_count = 0

    # Lặp cho đến khi không thể tạo thêm palindrome nào
    while len(arr) >= 3:
        # Bước 3: Chọn các ký tự xuất hiện ít nhất 2 lần để làm đầu/cuối
        available_x = [char for char, count in freq_dict.items() if count >= 2]
        available_y = [char for char, count in freq_dict.items() if count % 2 == 1]

        # Nếu không có đủ ký tự để tạo palindrome, dừng lại
        if not available_x or not available_y:
            break

        # Bước 4: Chọn `x` và `y` để tạo palindrome `xyx`
        x = available_x[0]  # Chọn ký tự xuất hiện nhiều lần đầu tiên
        y = available_y[0]  # Chọn ký tự xuất hiện lẻ đầu tiên

        # Giảm số lượng ký tự x và y trong từ điển
        freq_dict[x] -= 2
        freq_dict[y] -= 1

        # Xóa các ký tự đã dùng khỏi mảng NumPy
        arr = arr[arr != x]  # Xóa tất cả x
        arr = arr[arr != y]  # Xóa một lần y

        # Cập nhật số lần xuất hiện trong freq_dict
        if freq_dict[x] == 0:
            del freq_dict[x]
        if freq_dict[y] == 0:
            del freq_dict[y]

        # Tăng số lượng palindrome tìm được
        palindrome_count += 1

    return palindrome_count

# 🔹 Test cases
print(solution("aaaabc"))  # ✅ Output: 2 ("aba", "aca")
print(solution("xyzvwy"))  # ✅ Output: 1 ("yxy" hoặc "wyw")
print(solution("dd"))      # ✅ Output: 0 (Không thể tạo palindrome 3 ký tự)
print(solution("fknfkn"))  # ✅ Output: 2 ("fnf", "knk")
print(solution("aaa"))     # ✅ Output: 1 ("aaa")
print(solution("abcd"))    # ✅ Output: 0 (Không thể tạo palindrome)


1
1
0
0


KeyError: 'a'

In [21]:
import numpy as np

def solution(S):
    arr = np.array(list(S))
    unique, counts = np.unique(arr, return_counts=True)
    char_counts = dict(zip(unique, counts))
    palindrome_count = 0

    while True:
        edge_chars = [char for char, cnt in char_counts.items() if cnt >= 2]
        center_chars = [char for char, cnt in char_counts.items() if cnt >= 1]
        if len(edge_chars) == 0 or len(center_chars) <= 1 and edge_chars[0] == center_chars[0]:
            break

        x = edge_chars[0]
        y_candidates = [c for c in center_chars if c != x]
        y = y_candidates[0] if y_candidates else x

        char_counts[x] -= 2
        char_counts[y] -= 1

        if char_counts[x] == 0:
            del char_counts[x]
        if char_counts.get(y, 0) == 0:
            char_counts.pop(y, None)

        palindrome_count += 1

    return palindrome_count

# Test cases
print(solution("aaaabc"))  # ✅ Output: 2
print(solution("xyzvwy"))  # ✅ Output: 1
print(solution("dd"))      # ✅ Output: 0
print(solution("fknfkn"))  # ✅ Output: 2
print(solution("aaa"))     # ✅ Output: 1
print(solution("abcd"))    # ✅ Output: 0


2
1
0
2
0
0


In [24]:
def solution(S):
    # Đếm số lượng từng ký tự trong chuỗi
    char_counts = {}
    for char in S:
        if char in char_counts:
            char_counts[char] += 1
        else:
            char_counts[char] = 1

    palindrome_count = 0

    # Lặp cho tới khi không thể tạo thêm palindrome
    while True:
        # Tìm ký tự làm cạnh (xuất hiện ít nhất 2 lần)
        edge_char = None
        for char in char_counts:
            if char_counts[char] >= 2:
                edge_char = char
                break

        # Tìm ký tự làm trung tâm (ít nhất 1 lần)
        center_char = None
        for char in char_counts:
            if char_counts[char] >= 1 and char != edge_char:
                center_char = char
                break

        # Nếu không có ký tự cạnh hoặc trung tâm phù hợp, dừng lại
        if edge_char is None or center_char is None:
            break

        # Giảm số lượng ký tự đã sử dụng
        char_counts[edge_char] -= 2
        char_counts[center_char] -= 1

        # Xóa ký tự nếu số lượng còn lại bằng 0
        if char_counts[edge_char] == 0:
            del char_counts[edge_char]
        if char_counts[center_char] == 0:
            del char_counts[center_char]

        # Tăng số lượng palindrome
        palindrome_count += 1

    return palindrome_count

# Test lại các cases
print(solution("aaaabc"))  # ✅ Output: 2
print(solution("xyzvwy"))  # ✅ Output: 1
print(solution("dd"))      # ✅ Output: 0
print(solution("fknfkn"))  # ✅ Output: 2
print(solution("aaa"))     # ✅ Output: 1
print(solution("abcd"))    # ✅ Output: 0


2
1
0
2
0
0


In [25]:
def solution(S):
    # Đếm số lần xuất hiện của các ký tự
    char_counts = {}
    for char in S:
        if char in char_counts:
            char_counts[char] += 1
        else:
            char_counts[char] = 1  # Đã sửa ở đây!

    palindrome_count = 0

    while True:
        # tìm ký tự xuất hiện >=2 lần làm cạnh (đầu và cuối)
        e_char = None
        for char in char_counts:
            if char_counts[char] >= 2:
                e_char = char
                break

        # tìm ký tự khác làm trung tâm
        c_char = None
        for char in char_counts:
            if char_counts[char] >= 1 and char != e_char:  # Đã sửa ở đây!
                c_char = char
                break

        # Không đủ ký tự để tạo palindrome
        if e_char is None or c_char is None:
            break

        # Trừ đi số ký tự đã dùng
        char_counts[e_char] -= 2
        char_counts[c_char] -= 1  # sửa "- =" thành "-="

        # xóa ký tự nếu hết
        if char_counts[e_char] == 0:  # thêm dấu ":"
            del char_counts[e_char]
        if char_counts[c_char] == 0:  # thêm dấu ":"
            del char_counts[c_char]

        palindrome_count += 1

    return palindrome_count

# Test cases:
print(solution("aaaabc"))  # ✅ Output: 2
print(solution("xyzvwy"))  # ✅ Output: 1
print(solution("dd"))      # ✅ Output: 0
print(solution("fknfkn"))  # ✅ Output: 2
print(solution("aaa"))     # ✅ Output: 1
print(solution("abcd"))    # ✅ Output: 0


2
1
0
2
0
0


In [28]:
def solution(A):
    n = len(A)
    if n < 2:
        return 0

    # Khởi tạo mảng DP với (n+1) hàng và 4 cột (0 đến 3 ô)
    dp = [[0]*4 for _ in range(n+1)]

    # Bắt đầu DP
    for i in range(2, n+1):
        for k in range(1, 4):
            # Không chọn ô tại i
            dp[i][k] = dp[i-1][k]
            # Chọn ô tại vị trí (i-2, i-1)
            dp[i][k] = max(dp[i][k], dp[i-2][k-1] + A[i-1] + A[i-2])

    # Kết quả tối ưu dùng tối đa 3 ô
    return dp[n][3]

# Test cases đề bài
print(solution([2, 3, 5, 2, 3, 4, 6, 4, 1]))  # Output: 25
print(solution([1, 5, 3, 2, 6, 6, 10, 4, 7, 2, 1]))  # Output: 35
print(solution([1, 2, 3, 3, 2]))  # Output: 10
print(solution([5, 10, 3]))  # Output: 15


25
35
10
15


In [30]:
# you can write to stdout for debugging purposes, e.g.
# print("this is a debug message")

def solution(A):
    # Implement your solution here
    # sorrt A
    # make 3 array
    n = len(A)
    if n < 2:
        return 0

    # Khởi tạo mảng DP với (n+1) hàng và 4 cột (0 đến 3 ô)
    arr = [[0]*4 for _ in range(n+1)]

    for i in range(2, n+1):
        for k in range(1, 4):
            arr[i][k] = arr[i-1][k]
            arr[i][k] = max(arr[i][k], arr[i-2][k-1] + A[i-1] + A[i-2])

    return arr[n][3]
# Test cases đề bài
print(solution([2, 3, 5, 2, 3, 4, 6, 4, 1]))  # Output: 25
print(solution([1, 5, 3, 2, 6, 6, 10, 4, 7, 2, 1]))  # Output: 35
print(solution([1, 2, 3, 3, 2]))  # Output: 10
print(solution([5, 10, 3]))  # Output: 15


25
35
10
15


In [36]:
def solution(A):
    # Bước 1: tạo các cặp số liền nhau trong mảng
    pairs = []
    for i in range(len(A)-1):
        pairs.append([A[i], A[i+1]])
    # Bước 2: sắp xếp các cặp theo tổng từ lớn nhất đến nhỏ nhất
    pairs_sorted = sorted(pairs, key=lambda x: sum(x), reverse=True)
    # Bước 3: trả về 3 cặp lớn nhất (hoặc ít hơn nếu không đủ)
    return pairs_sorted[:3]






print(solution([2, 3, 5, 2, 3, 4, 6, 4, 1]))  # Output: 25
print(solution([1, 5, 3, 2, 6, 6, 10, 4, 7, 2, 1]))  # Output: 35
print(solution([1, 2, 3, 3, 2]))  # Output: 10
print(solution([5, 10, 3]))  # Output: 15


[[4, 6], [6, 4], [3, 5]]
[[6, 10], [10, 4], [6, 6]]
[[3, 3], [2, 3], [3, 2]]
[[5, 10], [10, 3]]


In [1]:
#!/bin/python3

import math
import os
import random
import re
import sys
import numpy as np

#
# Complete the 'countApplesAndOranges' function below.
#
# The function accepts following parameters:
#  1. INTEGER s start point
#  2. INTEGER t end point
#  3. INTEGER a
#  4. INTEGER b
#  5. INTEGER_ARRAY apples
#  6. INTEGER_ARRAY oranges
#

def countApplesAndOranges(s, t, a, b, apples, oranges):
    # Write your code here
    apples = np.array(apples)
    oranges = np.array(oranges)

    #sam_house = np.arange(s,t+1)

    location_apple_down = apples + a
    location_organes_down = oranges + b


    number_apple_in_house = np.sum((location_apple_down >= s ) & (location_apple_down <= t))
    number_organ_in_house = np.sum((location_organes_down >= s ) & (location_organes_down <= t))



    return number_apple_in_house,number_organ_in_house



    return number_apple_in_house,number_organ_in_house

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    s = int(first_multiple_input[0])

    t = int(first_multiple_input[1])

    second_multiple_input = input().rstrip().split()

    a = int(second_multiple_input[0])

    b = int(second_multiple_input[1])

    third_multiple_input = input().rstrip().split()

    m = int(third_multiple_input[0])

    n = int(third_multiple_input[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)

    print(*countApplesAndOranges(s, t, a, b, apples, oranges))

KeyboardInterrupt: Interrupted by user

In [2]:
def countApplesAndOranges(s, t, a, b, apples, oranges):
    count_a = 0
    count_b = 0

    # Đếm số quả táo rơi vào nhà
    for apple in apples:
        f = a + apple
        if s <= f <= t:
            count_a += 1

    # Đếm số quả cam rơi vào nhà
    for orange in oranges:
        f = b + orange
        if s <= f <= t:
            count_b += 1

    # In kết quả
    print(count_a)
    print(count_b)

In [ ]:
    num_apple = [ i + a for i in apples]
    num_organ = [i + b for i in oranges]
    count_a = 0
    count_b = 0
    for i in num_apple:
        if i>=s and i<=t:
            count_a = count_a + 1
        else:
            pass
    for i in num_organ:
        if i >= s and i <= t:
            count_b = count_b + 1
        else:
            pass
    print('{}\n{}'.format(count_a,count_b))